import { describe, it, expect } from 'vitest';
import { generateLayerLines } from './lineGenerator';
import type { LayerParams, NoiseFn } from './types';

const straightLayer: LayerParams = {
  color: '#00ff00',
  baseAngle: 0,
  noiseScale: 0.01,
  noiseStrength: 0,
  spacing: 20,
  weight: 1,
  alpha: 1,
  seed: 0,
};

const neutralNoise: NoiseFn = () => 0.5;

describe('generateLayerLines', () => {
  it('produces at least one line covering a 200x200 canvas', () => {
    const lines = generateLayerLines(straightLayer, 200, 200, neutralNoise);
    expect(lines.length).toBeGreaterThan(0);
  });

  it('moves in a straight horizontal line when noiseStrength is 0 and baseAngle is 0', () => {
    const lines = generateLayerLines(straightLayer, 200, 200, neutralNoise);
    const line = lines.find((l) => l.some((p) => Math.abs(p.y - 100) < 1));
    expect(line).toBeDefined();
    const uniqueYs = new Set(line!.map((p) => Math.round(p.y)));
    expect(uniqueYs.size).toBe(1);
  });

  it('keeps every point of every line within the canvas bounds', () => {
    const lines = generateLayerLines(straightLayer, 200, 200, neutralNoise);
    for (const line of lines) {
      for (const point of line) {
        expect(point.x).toBeGreaterThanOrEqual(-0.001);
        expect(point.x).toBeLessThanOrEqual(200.001);
        expect(point.y).toBeGreaterThanOrEqual(-0.001);
        expect(point.y).toBeLessThanOrEqual(200.001);
      }
    }
  });

  it('produces more lines when spacing is smaller', () => {
    const wideSpacing = generateLayerLines(straightLayer, 200, 200, neutralNoise);
    const tightSpacing = generateLayerLines({ ...straightLayer, spacing: 5 }, 200, 200, neutralNoise);
    expect(tightSpacing.length).toBeGreaterThan(wideSpacing.length);
  });

  it('resumes as a new segment when a line exits and later re-enters the canvas', () => {
    const width = 200;
    const height = 200;

    const curvingLayer: LayerParams = {
      color: '#ff00ff',
      baseAngle: 0,
      noiseScale: 1,
      noiseStrength: 180,
      spacing: 1000,
      weight: 1,
      alpha: 1,
      seed: 0,
    };

    // A deterministic, stateful noise function driven by a call counter:
    // straight (entering the canvas) -> turn down and exit through the
    // bottom -> turn back up and re-enter -> straight again far to the
    // right. This mimics a high noiseStrength curving the line back into
    // the canvas after it has left. The counter resets whenever x < 0,
    // which happens exactly once per parallel start point (each begins
    // its walk off-canvas to the left), keeping the three start points
    // generated by this layer's spacing independent of one another.
    const STRAIGHT_CALLS = 22; // x: ~0 -> ~90 (still straight along baseAngle)
    const DOWN_CALLS = 30; // turn +90deg: y: 100 -> 220 (exits through the bottom)
    const UP_CALLS = 7; // turn -90deg: y: 220 -> 192 (re-enters the canvas)
    let counter = 0;
    const curvingNoise: NoiseFn = (x) => {
      if (x < 0) {
        counter = 0;
        return 0.5;
      }
      counter++;
      if (counter <= STRAIGHT_CALLS) return 0.5; // deviation 0 -> straight along baseAngle
      if (counter <= STRAIGHT_CALLS + DOWN_CALLS) return 0.75; // deviation +90 -> turn down
      if (counter <= STRAIGHT_CALLS + DOWN_CALLS + UP_CALLS) return 0.25; // deviation -90 -> turn up
      return 0.5; // deviation 0 -> resume straight along baseAngle
    };

    const lines = generateLayerLines(curvingLayer, width, height, curvingNoise);

    // Segment 1: the initial straight approach along y ~ 100 (x < 50),
    // before the walk curves down and exits through the bottom edge.
    const segment1 = lines.find((line) =>
      line.some((p) => Math.abs(p.y - 100) < 1 && p.x < 50)
    );
    expect(segment1).toBeDefined();

    // Segment 2: only reachable if the walk resumed tracing after exiting
    // through the bottom and re-entering near y ~ 200, then travelling
    // straight far to the right (x > 150). Segment 1 never reaches
    // x > 150 (it stalls at x ~ 90 while curving down and back up), so
    // this region can only be covered by a freshly-started segment after
    // re-entry.
    const segment2 = lines.find((line) => line.some((p) => p.x > 150));
    expect(segment2).toBeDefined();

    // They must be genuinely distinct polylines in the returned array,
    // proving the walk was split into multiple segments rather than
    // truncated at the first exit.
    expect(segment2).not.toBe(segment1);
  });
});
